name: Actualizacion Automatica de Vacantes

on:
  schedule:
    # 7:00 AM hora de Perú (PET es UTC-5), por lo que debe ejecutarse exactamente a las 12:00 UTC, todos los días
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v3

      - name: Inicializar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias Unificadas
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Ejecutar Extractor de Mercado
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scraper.py
